document.getElementById("myH1").textContent = `Star Rail Optimizer`;
document.getElementById("myP").textContent = ``;
document.getElementById("relicRarity").onchange = {};

console.log(relicMainData);
console.log(relicSubData1);
console.log(relicSetsData);
console.log(relicAscenscionData);
console.log(characterOption);
console.log(charNames);
console.log(relicSlots);
console.log(relicRarities);
console.log(relicAscenscions);
console.log(relicSets);
console.log(relicMainStats);
console.log(relicMainStatValues);
console.log(relicSubStats1);
console.log(relicSubStatValues1);
console.log(relicSubStatRollsValues1);
console.log(relicSubStats2);
console.log(relicSubStatValues2);
console.log(relicSubStatRollsValues2);
console.log(relicSubStats3);
console.log(relicSubStatValues3);
console.log(relicSubStatRollsValues3);
console.log(relicSubStats4);
console.log(relicSubStatValues4);
console.log(relicSubStatRollsValues4);
console.log(getElementById("relicSlot"));
console.filter(CharacterData.charNames);
